# Generated by Django 3.0 on 2019-12-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50, verbose_name='驾驶人')),
                ('driver_license_number', models.CharField(max_length=100, verbose_name='驾驶证号')),
                ('driver_phone', models.CharField(max_length=100, verbose_name='驾驶人手机号')),
                ('vehicle_number', models.CharField(max_length=100, verbose_name='车牌号码')),
                ('vehicle_plate_color', models.IntegerField(choices=[(1, '黄牌'), (2, '蓝牌'), (3, '绿牌')], verbose_name='车牌颜色')),
                ('vehicle_category', models.IntegerField(choices=[(1, '小型客车'), (2, '大型客车'), (3, '小型货车'), (4, '大型货车')], verbose_name='车辆类型')),
                ('vehicle_mass', models.IntegerField(verbose_name='车辆质量')),
                ('category', models.IntegerField(choices=[(1, '危险品运输'), (2, '海产品运输'), (3, '渣土运输')], verbose_name='通行证类别')),
                ('start_point', models.CharField(blank=True, max_length=50, null=True, verbose_name='通行证起点')),
                ('end_point', models.CharField(blank=True, max_length=50, null=True, verbose_name='通行证终点')),
                ('via_point', models.TextField(blank=True, null=True, verbose_name='通行证途经点')),
                ('transit_start_time', models.TimeField(verbose_name='通行证规定开始通行时间')),
                ('transit_end_time', models.TimeField(verbose_name='通行证规定截止通行时间')),
                ('validity_category', models.IntegerField(choices=[(1, '一天'), (2, '三天'), (3, '一个月')], verbose_name='通行证有效期类型')),
                ('effective_time', models.DateTimeField(auto_now_add=True, verbose_name='通行证生效时间')),
                ('ineffective_time', models.DateTimeField(verbose_name='通行证失效时间')),
                ('route_change_times', models.IntegerField(blank=True, choices=[(1, '一次'), (2, '两次'), (3, '三次')], default=3, verbose_name='通行证剩余线路修改次数')),
                ('register_channel', models.IntegerField(choices=[(1, '微信端'), (2, 'PC端')], verbose_name='通行证注册渠道')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='数据更新时间')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='数据有效性')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='数据备注信息')),
            ],
            options={
                'verbose_name': '通行证信息表',
                'verbose_name_plural': '通行证信息表',
            },
        ),
    ]
