# Generated by Django 3.0 on 2019-12-17 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_permit', '0003_remove_trafficpermit_ineffective_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficPermitCategoryTransitTimeRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_permit_category', models.IntegerField(choices=[(1, '危险品运输'), (2, '海产品运输'), (3, '渣土运输')], verbose_name='通行证类型')),
                ('transit_start_time', models.TimeField(verbose_name='开始通行时间')),
                ('transit_end_time', models.TimeField(verbose_name='截止通行时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='数据更新时间')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='数据有效性')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='数据备注信息')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=100, verbose_name='单位编号')),
                ('unit_name', models.CharField(max_length=100, verbose_name='单位名称')),
                ('unit_category', models.IntegerField(choices=[(1, '国营单位'), (2, '私营单位')], verbose_name='单位类别')),
                ('unit_address', models.TextField(verbose_name='单位地址')),
                ('unit_phone', models.CharField(max_length=100, verbose_name='单位电话')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='数据更新时间')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='数据有效性')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='数据备注信息')),
            ],
        ),
        migrations.RenameField(
            model_name='trafficpermit',
            old_name='category',
            new_name='traffic_permit_category',
        ),
        migrations.AddField(
            model_name='trafficpermit',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='units', to='traffic_permit.Unit', verbose_name='所属单位'),
        ),
    ]
