# Generated by Django 3.0 on 2019-12-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_permit', '0004_auto_20191217_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_principal',
            field=models.CharField(default=0, max_length=100, verbose_name='单位负责人'),
            preserve_default=False,
        ),
    ]
