# Generated by Django 3.0 on 2019-12-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_permit', '0007_auto_20191217_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='standard',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否为标杆单位'),
        ),
    ]
