# Generated by Django 3.0 on 2019-12-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_permit', '0008_unit_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficpermit',
            name='traffic_permit_status',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '紧急情况冻结'), (3, '天气重污染冻结'), (4, '排放超标冻结'), (5, '企业关联冻结')], default=1),
        ),
    ]
