# Generated by Django 3.0 on 2019-12-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_permit', '0009_trafficpermit_traffic_permit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_status',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '失信冻结')], default=1),
        ),
    ]
