# Generated by Django 3.0 on 2019-12-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_permit', '0010_unit_unit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='unit_number',
        ),
    ]
