# Generated by Django 3.0 on 2019-12-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_permit', '0011_remove_unit_unit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficpermitcategorytransittimerel',
            name='traffic_permit_category',
            field=models.IntegerField(choices=[(1, '危险品运输'), (2, '海产品运输'), (3, '渣土运输')], unique=True, verbose_name='通行证类型'),
        ),
    ]
