# Generated by Django 3.0 on 2019-12-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_permit', '0012_auto_20191218_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficpermitcategorytransittimerel',
            options={'verbose_name': '通行证种类允许通行时间关联表', 'verbose_name_plural': '通行证种类允许通行时间关联表'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': '单位信息表', 'verbose_name_plural': '单位信息表'},
        ),
    ]
